version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zyuz-backend
    ports:
      - "5169:5169"
      - "7106:7106"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5169;https://+:7106
      - ASPNETCORE_HTTPS_PORT=7106
      - ASPNETCORE_Kestrel__Certificates__Default__Password=contraseña
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=zyuz_database_local;User=root;Password=2634;
    env_file: /backend/.env
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https/
    networks:
      - zyuz-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zyuz-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - zyuz-net

networks:
  zyuz-net:
    driver: bridge